version: "3.9"

services:
  php:
    build:
      context: ./ops/php
    container_name: ns-php
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./ops/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_HOST: db
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_DATABASE: netasamp
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
      BROADCAST_DRIVER: log
      SCOUT_DRIVER: meilisearch
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: masterKey
      FILESYSTEM_DISK: s3
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: ap-south-1
      AWS_BUCKET: netasamp-local
      AWS_URL: http://minio:9000
      AWS_ENDPOINT: http://minio:9000
      AWS_USE_PATH_STYLE_ENDPOINT: "true"
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
    depends_on:
      - db
      - redis
      - meilisearch
      - minio
      - mailhog

  web:
    image: nginx:stable-alpine
    container_name: ns-web
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  queue:
    build:
      context: ./ops/php
    container_name: ns-queue
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./ops/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    command: sh -lc "php artisan horizon"
    environment:
      QUEUE_CONNECTION: redis
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - php
      - redis
      - db

  scheduler:
    build:
      context: ./ops/php
    container_name: ns-scheduler
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./ops/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    command: sh -lc "php artisan schedule:work"
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - php
      - redis
      - db

  db:
    image: postgres:16-alpine
    container_name: ns-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netasamp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ns-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:v1.8
    container_name: ns-meilisearch
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: masterKey
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

  minio:
    image: quay.io/minio/minio:RELEASE.2024-07-26T20-56-39Z
    container_name: ns-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: ns-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:
  redis_data:
  meili_data:
  minio_data:
